version: "3"

services:
    bdbapp:
        build: ./BDBdemowithflask/src
        container_name: BigChainDBPOC
        #restart: always
        volumes:
          - ./BDBdemowithflask/src:/code
        network_mode: "host"
        depends_on:
          - redis
        environment:
          - REDIS_HOST=redis
          - REDIS_PORT=6379
    pydapp:
        build: ./PyDapp/src/
        container_name: RRCoinDapp
        volumes:
          - ./PyDapp/src/:/code
        network_mode: "host"
        depends_on:
          - redis
    redis:
        image: redis:3.2-alpine
        container_name: RedisDBPOC
        volumes:
          - redis_data:/data
        network_mode: "host"
volumes:
    redis_data:
